name: radio_app_v2
description: A new Radio App for streaming radio_app_v2 station.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 9.0.1+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1

  http: ^1.1.0

  #Launcher 
  flutter_native_splash: ^2.2.10+1
  url_launcher: ^6.1.6
  just_audio: ^0.9.29
  just_audio_background: ^0.0.1-beta.7
  permission_handler: ^10.0.2
  share_plus: ^4.4.0

flutter_native_splash:
  color: "#ffffff"
  image_path: assets/icons.png
  android: "launcher_icon"
  ios: true

  #Launch phone
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

  #Audio playing packages
  just_audio_background: ^0.0.1-beta.7
  just_audio: ^0.9.29

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/